# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Benthic < Formula
  desc "CLI for interacting with Benthic Cloud"
  homepage "https://benthic.cloud"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.3/benthic-cli_Darwin_arm64.tar.gz"
      sha256 "e997e1b2764d204ca38e6a356f62658673b1f901ff19009b3eb8d5e4ef2accc5"

      def install
        bin.install "benthic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.3/benthic-cli_Darwin_x86_64.tar.gz"
      sha256 "d202526c5147665dece165c8920f16644b104b04433e14dd2b78b86ce95d11d3"

      def install
        bin.install "benthic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.3/benthic-cli_Linux_arm64.tar.gz"
      sha256 "dd9d9b9ea7ac7c095b649d7ad759a20c29a5d206476cc4e44317874341dd487a"

      def install
        bin.install "benthic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.3/benthic-cli_Linux_x86_64.tar.gz"
      sha256 "015e17715cd6429d078267cd3c46bd185fad7cae50a337ef792a53b038f14681"

      def install
        bin.install "benthic"
      end
    end
  end

  test do
    system "#{bin}/benthic --version"
  end
end
