# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Benthic < Formula
  desc "CLI for interacting with Benthic Cloud"
  homepage "https://benthic.cloud"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.4/benthic-cli_Darwin_arm64.tar.gz"
      sha256 "b14516968dfd1a3cc0a6cf9f8a500641ad8f459ce61fd0ade4f5f43896c778de"

      def install
        bin.install "benthic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.4/benthic-cli_Darwin_x86_64.tar.gz"
      sha256 "a1043a32853440922e2e0694d3879da02a41d4873ab233136921e2c0d4e7c06c"

      def install
        bin.install "benthic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.4/benthic-cli_Linux_arm64.tar.gz"
      sha256 "5a43fc88e98197ca612158a1e20583618f25a45791ecab37353c7944507b6f11"

      def install
        bin.install "benthic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/benthic-cloud/benthic-cli/releases/download/0.0.4/benthic-cli_Linux_x86_64.tar.gz"
      sha256 "110487782cfaea9c51353b80cc85507496afb25d4abefbd9f4e45546158cd347"

      def install
        bin.install "benthic"
      end
    end
  end

  test do
    system "#{bin}/benthic --version"
  end
end
